name: flame_extend
description: A Flame extend lib
version: 0.0.1
homepage: https://github.com/dinoandcat/flame_extend

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^0.26.0
  box2d_flame: ^0.4.6
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.9.4
